### ISSUE TITLE
instructions for running locally

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/MyHbarWallet#414]
It's likely more secure for technical users to run MHW locally rather than access via a browser

I think it'd be helpful to include easy instructions for how to do so

Also in the spirit of OSS & wanting contributions/other projects to leverage this codebase it could help lower the barrier to entry

**Comment by lukewoolh** [comment]
I agree, I spent some time trying to build this without success. I understand it's the developer's prerogative to be across yarn, node etc, but even some supportive documentation to steer in the right direction would be great.

**Comment by mehcode** [comment]
cc @cacampbell 

---

I believe `master` is stuck on Node 10.x and _requires_ `yarn`. It's been awhile since I've played with it though. We're currently deep in the middle of a large refactor to the codebase (and adding support for HTS 🎉 ). Once we get over that, we'll make sure we have good docs for running it locally. In the refactor we've already fixed the dependency on older Node.
