### ISSUE TITLE
Separate state from props in Modals

### ISSUE THREAD

**Issue by Sheng-Long** [hashgraph/MyHbarWallet#91]

**Comment by cacampbell** [comment]
over my dead body :unamused:

**Comment by QuestofIranon** [comment]
I don't think this is doable without a complete overhaul.

**Comment by cacampbell** [comment]
it wouldn't be impossible, but would require touch every single modal and view that uses modals. There isn't really a case where we do more than trivial binding to modal props from views, which is both an argument for and against doing the refactor. On one hand, it wouldn't be complicated (just tedious), but on the other, I am not sure what we gain aside from ideological purity. :man_shrugging:

**Comment by QuestofIranon** [comment]
The general consensus on slack was that we just need to update a few modals to use the emitter pattern and eventually switch over to using `tsx`.

**Comment by cacampbell** [comment]
okay so where did we land on "modifying props is haram"?

**Comment by QuestofIranon** [comment]
The state passed in as props shouldn't be directly edited in the modal but in the parent context due to "undefined behavior" and Two-Way binding is technically deprecated in vue 2.0. Any state change should be done through the emitter pattern. The main problem is that we are updating state passed as a prop in a child and then relying on that state change in the parent.

It's not a huge priority to change since we will eventually be removing most of the modals and likely switching to `tsx` based components anyway.

**Comment by QuestofIranon** [comment]
The problem with this issue was that it is too broad and doesn't mention any of the modals where this is an issue. This one should either be updated with a checklist of modals that need "fixed" or a new issue should be created.

**Comment by cacampbell** [comment]
ah this explains why some modals have a handle change that seems completely redundant for their v-model. oh no.
